### PR TITLE
Fix, test and travis

### PR DESCRIPTION
**Pull request by guilhem**
- Fix error when /etc/local-gen doesn't exist
- Fix locales not available
- Cleanup LWRP
- Fix foodcrtic
- Add rubcop
- Add travis
- Add kitchen test
- Add strainer to launch all tests

```
$ bundle exec strainer test
```

### CODE REVIEW

**Comment by guilhem** [comment]
@phbergsmann This patch is quite important for PostgreSQL cookbook.

For now, PostgreSQL can't be installed on a fresh Ubuntu if your locale isn't generated.
My patch add generation of any locale used.

It also fix a major bug with your previous patch when, on a default fresh install, /etc/locale-gen doesn't exist.

I add test and feature.

Also, you can enable Travis for this repo.

**Comment by phbergsmann** [comment]
@guilhem First of all thx for your contributions! But I'm afraid you removed the debian-compatibility again? update-locale LANG=#{high_locale(locale)} won't install a locale in debian. AFAIK the only possibility without any user-input is to add it to /etc/locale.gen. I'll try to setup a test-environment so I can fix the cookbook to work with debian and ubuntu. Thx for your contributions in the testing-area! I'll add travis right now!

**Comment by guilhem** [comment]
Hi @phbergsmann ,

I think that `locale-gen #{locale}` is true on any Linux system (glibc), I don't use `update-locale` for "add" action ;-) (and you don't change it for "set")

I will add a way to populate /etc/locale-gen tomorrow, but for now, I'm quite sure that my patch works ;-)
locale-gen must only be used by "locales" upgrade.

**Comment by guilhem** [comment]
@phbergsmann I just add debian testing and it seems to work.

**Comment by guilhem** [comment]
@phbergsmann my last patch fix postgresql installation

I look at 'locale' cookbook here https://github.com/hw-cookbooks/locale/blob/master/recipes/default.rb

And as you can see, they are doing same as me :)

**Comment by guilhem** [comment]
:up:

**Comment by guilhem** [comment]
:up: :angel:

**Comment by BarthV** [comment]
:up: :cat:

**Comment by michaelkirk** [comment]
What's keeping this from being merged?

**Comment by guilhem** [comment]
:up: !

**Comment by BarthV** [comment]
mega :up: ... I'm running Berks hack pointing to @guilhem fork for too long.

**Comment by phbergsmann** [comment]
Hi

I'm sorry it took so long, but I didn't find the time to dive into that...

First of all: I can't merge this pull-request since it destroys debian compatibility as I said. @guilhem s test only tests if the cookbook default recipe works, but doesn't actually test anything.

I've fixed the problems with ubuntu on the development branch and included some real integration tests.

@guilhem Could you rebase your pull-request to the latest commit in develop branch and fix it, so the tests pass? Right now it adding multiple locales on debian does not work - I have written that down in issue #19

**Comment by guilhem** [comment]
@phbergsmann I found the problem and will fix it this afternoon.
Will work for ubuntu / rhel etc ;)

**Comment by guilhem** [comment]
Look at #20

**Pull request closed without merging**
